# .github/release.yml

  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]
  categories:
    - title: Current version: 
    - title: 🚀 Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🚀 Breaking Changes
      labels:
        - breaking-change
    - title: Other Changes
      labels:
        - "*" # Catch-all for pull requests that didn't match any of the previous categories
